# Generated by Django 4.1.4 on 2022-12-12 14:45

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/profile.jpg', upload_to=authentication.models.img_path),
        ),
    ]
